name: relax
description: Ease of choosing and blending the ambient sounds into a mixture that will perfectly fit your mood.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  
  google_fonts: ^1.1.1
  
  audioplayers: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_native_splash: ^0.1.9
#   flutter_launcher_icons: ^0.8.1 
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "images/ic_launcher.png"
# flutter_native_splash:
#   image: images/splasw.png
#   color: "#55b9f3"


  
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/audio/

